CREATE TABLE Usuarios (
    Id  UNIQUEIDENTIFIER DEFAULT NEWID() PRIMARY KEY,
    Nome VARCHAR(50) NOT NULL UNIQUE,
    SenhaHash VARCHAR(MAX) NOT NULL, 
    Email VARCHAR(100),
    DataCriacao DATETIME DEFAULT GETDATE()
);

CREATE TABLE CidadesFavoritas (
    id UNIQUEIDENTIFIER DEFAULT NEWID() PRIMARY KEY,
    cidadeid INT NOT NULL, 
    nome NVARCHAR(100) NOT NULL,
    state NVARCHAR(10) NOT NULL,
    usuarioId NVARCHAR(200) NOT NULL
);

